# ==========================================
# 1. APPLICATION METADATA
# ==========================================

#Info of Replication:
replicaCount: 1

# ==========================================
# 2. TCP/CLUSTERIP
# ==========================================

internalTrafficPolicy: Cluster
ipFamilyPolicy: SingleStack
typeTCP: ClusterIP

# ==========================================
# 3. INGRESS/NGINX
# ==========================================

ingressClassName: nginx
pathType: Prefix

# ==========================================
# 4. REGISTRY / DOCKER HUB
# ==========================================
