apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - backend:
             service:
              name: {{ .Values.name }}-serivce
              port:
                number: {{ .Values.secret.portService }}
            path: /
            pathType: {{ .Values.pathType }}
