apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- if .Values.secret.enabled }}
stringData:
  SQLSERVER_HOST: "{{ .Values.secret.host }}"
  SQLSERVER_DB: "{{ .Values.secret.namedb }}"
  SQLSERVER_PORT: '{{ .Values.secret.port }}'
  SQLSERVER_USERNAME: "{{ .Values.secret.username }}"
  SQLSERVER_PASSWORD: "{{ .Values.secret.pswd }}"
  PORT_SERVICE: '{{ .Values.secret.portTarget }}'
  NAME_SERVICE: "{{ .Values.secret.nameservice }}"
{{- end }}
